name: Build and Upload Artifact

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest  # We use Windows runner as MSBuild is used

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Setup MSBuild
       # uses: microsoft/setup-msbuild@v1.0.2  # Set up MSBuild on the Windows runner
      
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version:      5.15.2
          host:         windows
          target:       desktop
          arch:         win64_msvc2019_64
          dir:          ${{ runner.temp }}
          setup-python: false

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64
      
      - name: Set up Qt Environment and Run MSBuild
        run: |
          $env:QTDIR = "${{ runner.temp }}/Qt/5.15.2/msvc2019_64"
          $env:PATH = "${{ runner.temp }}/Qt/5.15.2/msvc2019_64/bin;$env:PATH"
          $env:INCLUDE = "${{ runner.temp }}/Qt/5.15.2/msvc2019_64/include;$env:INCLUDE"
          $env:LIB = "${{ runner.temp }}/Qt/5.15.2/msvc2019_64/lib;$env:LIB"
          msbuild path/to/your/solution.sln /p:Configuration=Debug /p:Platform=x64

      
      - name: Build the solution
        run: 
          msbuild ${{ github.workspace }}\native\src\ReachVariantTool.sln /p:Configuration=Debug /p:Platform=x64

      - name: Create artifact directory
        run: mkdir artifact

      - name: Copy built files to artifact directory
        run: |
          robocopy x64\Debug artifact /E

      - name: Zip artifact directory
        run: |
          $zipPath = $env:GITHUB_WORKSPACE + '\artifact.zip'
          Compress-Archive -Path $env:GITHUB_WORKSPACE\artifact -DestinationPath $zipPath

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: project-artifact
          path: artifact.zip
